package be.kuleuven.shamrock.interactivemap;

public class TemplaticIcon extends Icon {

    public enum Type {
        ACCOUNTANCY("templatic/accountancy.png"),
        ARTS_CRAFTS("templatic/arts-crafts.png"),
        ASTROLOGY("templatic/astrology.png"),
        AUTOMOTIVE("templatic/automotive.png"),
        BARS("templatic/bars.png"),
        BIRDS("templatic/birds.png"),
        BOOKS_MEDIA("templatic/books-media.png"),
        BREAKFAST_N_BRUNCH("templatic/breakfast-n-brunch.png"),
        BUSINESS("templatic/business.png"),
        CAKE_SHOP("templatic/cake-shop.png"),
        CLOTHINGS("templatic/clothings.png"),
        CLUBS("templatic/clubs.png"),
        COFFEE_N_TEA("templatic/coffee-n-tea.png"),
        COMMERCIAL_PLACES("templatic/commercial-places.png"),
        COMMUNITY("templatic/community.png"),
        COMPUTERS("templatic/computers.png"),
        CONCERTS("templatic/concerts.png"),
        COOKBOOKS("templatic/cookbooks.png"),
        DANCE_CLUBS("templatic/dance-clubs.png"),
        DEFAULT("templatic/default.png"),
        DENTAL("templatic/dental.png"),
        DOCTORS("templatic/doctors.png"),
        EDUCATION("templatic/education.png"),
        ELECTRONICS("templatic/electronics.png"),
        EMPLOYMENT("templatic/employment.png"),
        ENGINEERING("templatic/engineering.png"),
        ENTERTAINMENT("templatic/entertainment.png"),
        EVENT("templatic/event.png"),
        EXHIBITIONS("templatic/exhibitions.png"),
        FASHION("templatic/fashion.png"),
        FESTIVALS("templatic/festivals.png"),
        FINANCIAL_SERVICES("templatic/financial-services.png"),
        FOOD("templatic/food.png"),
        FURNITURE_STORES("templatic/furniture-stores.png"),
        GAMES("templatic/games.png"),
        GIFTS_FLOWERS("templatic/gifts-flowers.png"),
        GOVERNMENT("templatic/government.png"),
        HALLOWEEN("templatic/halloween.png"),
        HEALTH_MEDICAL("templatic/health-medical.png"),
        HOME_SERVICES("templatic/home-services.png"),
        HOTELS("templatic/hotels.png"),
        INDUSTRIES("templatic/industries.png"),
        INTERNET("templatic/internet.png"),
        JEWELRY("templatic/jewelry.png"),
        JOBS("templatic/jobs.png"),
        KARAOKE("templatic/karaoke.png"),
        LAW("templatic/law.png"),
        LAWN_GARDEN("templatic/lawn-garden.png"),
        LIBRARIES("templatic/libraries.png"),
        LOCAL_SERVICES("templatic/local-services.png"),
        LOUNGES("templatic/lounges.png"),
        MAGAZINES("templatic/magazines.png"),
        MANUFACTURING("templatic/manufacturing.png"),
        MARKER_NEW1_12("templatic/marker-new1_12.png"),
        MASS_MEDIA("templatic/mass-media.png"),
        MASSAGE_THERAPY("templatic/massage-therapy.png"),
        MATRIMONIAL("templatic/matrimonial.png"),
        MEDICAL("templatic/medical.png"),
        MEETUPS("templatic/meetups.png"),
        MISCELLANEOUS_FOR_SALE("templatic/miscellaneous-for-sale.png"),
        MOBILE_PHONES("templatic/mobile-phones.png"),
        MOVIES("templatic/movies.png"),
        MUSEUMS("templatic/museums.png"),
        MUSICAL_INSTRUMENTS("templatic/musical-instruments.png"),
        MUSICAL("templatic/musical.png"),
        NIGHTLIFE("templatic/nightlife.png"),
        PARKS("templatic/parks.png"),
        PARTIES("templatic/parties.png"),
        PETS("templatic/pets.png"),
        PHOTOGRAPHY("templatic/photography.png"),
        PIZZA("templatic/pizza.png"),
        PLACES("templatic/places.png"),
        PLAY_SCHOOLS("templatic/play-schools.png"),
        PLAYGROUNDS("templatic/playgrounds.png"),
        POOL_HALLS("templatic/pool-halls.png"),
        PRINTING_GRAPHIC_ARTS("templatic/printing-graphic-arts.png"),
        PROFESSIONAL("templatic/professional.png"),
        REAL_ESTATE("templatic/real-estate.png"),
        RELIGIOUS_ORGANIZATIONS("templatic/religious-organizations.png"),
        RESIDENTIAL_PLACES("templatic/residential-places.png"),
        RESTAURANTS("templatic/restaurants.png"),
        RETAIL_STORES("templatic/retail-stores.png"),
        SALOON("templatic/saloon.png"),
        SCHOOLS("templatic/schools.png"),
        SCIENCE("templatic/science.png"),
        SHOPPING("templatic/shopping.png"),
        SPORTING_GOODS("templatic/sporting-goods.png"),
        SPORTS("templatic/sports.png"),
        SWIMMING_POOLS("templatic/swimming-pools.png"),
        TELEMARKETING("templatic/telemarketing.png"),
        TICKETS("templatic/tickets.png"),
        TIFFIN_SERVICES("templatic/tiffin-services.png"),
        TIRES_ACCESSORIES("templatic/tires-accessories.png"),
        TOOLS_HARDWARE("templatic/tools-hardware.png"),
        TOURS("templatic/tours.png"),
        TOYS_STORE("templatic/toys-store.png"),
        TRANSPORT("templatic/transport.png"),
        TRAVEL("templatic/travel.png"),
        TUTORS("templatic/tutors.png"),
        VACANT_LAND("templatic/vacant-land.png");

        private final String text;
        private Type(final String text) { this.text = text;}
        @Override
        public String toString() {return text;}
    }

    public TemplaticIcon(LeafletMap linkedMap, Type type) {
        super(linkedMap, type.toString(), 16, 44, 0 , -38);
    }

}
